name: Build and test on Linux

on:
  push:
    branches: [ master ]
  pull_request:

concurrency:
  # In master we want to run for every commit, in other branches — only for the last one
  group: ${{
    ( github.ref == 'refs/heads/master' &&
    format('{0}/{1}/{2}', github.workflow, github.ref, github.sha) )
    ||
    format('{0}/{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and run tests

    runs-on: [self-hosted, Linux, X64, aws_autoscaling]

    steps:
    # https://github.com/actions/checkout/issues/1552
    - name: Clean up after previous checkout
      run: chmod +w -R ${GITHUB_WORKSPACE}; rm -rf ${GITHUB_WORKSPACE}/*;

    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Build sources
      run: nix build -L

    - name: Run tests
      run: nix flake -L check
